---
# tasks file for java install

- name: Check for RPM File
  stat:
    path: "{{ rpm_upload_dir }}/{{ rpm_file }}"
  register: stat_result

- name: Upload RPM file
  copy:
    src: "{{ rpm_local_src_dir }}/{{ rpm_file }}"
    dest: "{{ rpm_upload_dir }}/{{ rpm_file }}"
    mode: u+rwx
  when: not stat_result.stat.exists

- name: Install java
  yum:
    name: "{{ rpm_upload_dir }}/{{ rpm_file }}"
    state: present
  become: yes
